# Generated by Django 4.1.7 on 2023-03-24 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reversion', '0004_alter_revision_id_alter_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='user',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='The user who created this revision.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
